### DISCUSSION TITLE
키바나를 도입하며 정리한 내용들 살펴보기

### DISCUSSION THREAD

**Discussion by thornscript** [GU-99/grow-up-pms#352] [기술 도입]
# 📘 오늘 알아본 내용
## 📝 키바나에 인증 메커니즘 도입하기
키바나를 기본적으로 설치하면 로그인과 같은 기능이 유료 서비스에 해당하는 xpack에 포함된 기능이라서, 이용하려면 트라이얼 버전을 이용해야 한다. 라이센스가 별도로 존재하건 트라이얼 버전을 이용 중이건 이 부분은 해결되었다고 가정하고 진행한다.

### 보안 활성화하기
먼저 로그인 기능을 활성화 하려면 xpack이 설치된 엘라스틱서치부터 설정을 해주어야 한다. `elasticsearch/config/elasticsearch.yml`을 열어서 아래와 같이 설정을 추가해주자.

```yml
xpack.security.enabled: true
```

그리고 키바나에서 접근할 수 있도록, 엘라스틱서치에서 계정을 따로 추가해야 한다.

```sh
$ bin/elasticsearch-users useradd kibana -p kibana -r superuser
```

마지막으로 키바나에서 방금 만든 계정 정보를 설정 파일에 넣어주면 된다. `kibana/config/kibana.yml`을 열어서 아래와 같이 두 줄을 추가해주자.

```yml
elasticsearch.username: kibana
elasticsearch.password: kibana
```

## 📝 파일비트 설치 및 구동 방법
파일비트는 실시간으로 파일의 내용을 수집해서 엘라스틱서치나 로그스태시 등으로 출력 결과를 전달하는 역할을 한다. 먼저 아래와 같이 입력해서 모니터링 하려는 서버에 파일비트를 설치하자.

```sh
# RPM
curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.16.1-x86_64.rpm
sudo rpm -vi filebeat-8.16.1-x86_64.rpm
```

그 후에 이렇게 설치한 파일비트를 엘라스틱서치에 연결해야 하는데, 연결 정보는 `/etc/filebeat/filebeat.yml`에 아래와 같이 작성하면 된다. 여기서 필요한 아이디랑 API 키를 어떻게 만드는지는 아래에서 설명된 부분을 참고해서 만들면 된다.

```yaml
output.elasticsearch:
  hosts: ["http://log.growup.kr:9200"]
  api_key: "id:api_key"
```

### 파일비트에 필요한 역할 만들기
엘라스틱서치에 이벤트를 발행하는 사용자는 파일비트 인덱스를 생성하고 쓸 수 있어야 한다. `Security > Roles`에서 새로운 역할을 생성해보자.

![image](https://github.com/user-attachments/assets/b2c01064-bbdc-4738-9ace-3c8da4bf8f4d)

아래의 권한들은 파일비트가 정상적으로 로그를 수집하고 엘라스틱서치에 저장하는 데 필요한 최소한의 권한들이다. 이에 대한 내용은 [이곳](https://www.elastic.co/guide/en/beats/filebeat/current/privileges-to-publish-events.html)에서 좀 더 확인해볼 수 있다.

| 권한명            | 설명                                                           |
| -------------- | ------------------------------------------------------------ |
| monitor        | 클러스터의 기본적인 상태 확인 가능                                          |
|                | 클러스터 버전, 상태 등의 정보를 볼 수 있는 권한                                 |
| read_ilm       | ILM(Index Lifecycle Management, 인덱스 수명 주기 관리) 정책을 읽을 수 있는 권한 |
|                | 인덱스의 생성, 관리, 삭제 등의 자동화 정책 확인 가능                              |
| read_pipeline  | 데이터 처리 파이프라인 설정을 읽을 수 있는 권한                                  |
|                | 파일비트 모듈이 데이터를 어떻게 처리할지 정의된 파이프라인 확인 가능                       |
| create_doc     | 인덱스에 새로운 문서(로그 데이터)를 쓸 수 있는 권한                               |
|                | 파일비트가 수집한 로그를 저장할 수 있게 함                                     |
| auto_configure | 인덱스의 설정을 자동으로 구성할 수 있는 권한                                    |
|                | 필요한 경우 인덱스 매핑이나 설정을 자동으로 업데이트                                |

### 파일비트에 필요한 사용자 만들기
이제 `Security > Users`에서 아까 생성한 역할을 기반으로 사용자를 생성하자.

![image](https://github.com/user-attachments/assets/8275b158-bf9e-48cc-bf0f-770ee3ca2b8a)

### 엘라스틱서치 API 키 만들기
이번에는 `Management > Dev Tools`로 이동하자. 여기서 아까 만들었던 계정의 이름과 비밀번호를 입력한 다음에 `id`와 `api_key`를 가져오면 된다.

```json
POST _security/api_key/grant
{
  "grant_type": "password",
  "username": "filebeat_internal",
  "password": "YOUR PASSWORD",
  "api_key": {
    "name": "filebeat_publisher"
  }
}
```

### 로그 데이터 수집하기
`/etc/filebeat/filebeat.yml`을 열어서 `filebeat.inputs`을 아래와 같이 수정해주자. 로그백에서 만들어진 INFO, ERROR, WARN 등의 로그를 파일비트에서 가져오도록 지정한다.

```yaml
# filestream은 기존의 log 입력 타입의 개선된 버전이다.
- type: filestream
  # 필수 필드이고 ID는 항상 고유해야 함
  id: api-log
  enabled: true
  # 경로는 가져오려는 로그가 위치한 곳이고 Glob 패턴을 사용할 수 있음
  paths:
    - /home/ec2-user/logs/info/*.json
  # 로그 이벤트를 분류하고 필터링하는데 사용되는 단순한 레이블
  tags: ["info"]
  # 더 구조화된 커스텀 필드를 추가할 때 사용
  # 로그 데이터에 대한 추가 컨텍스트를 제공하는 역할을 함
  fields:
    log_level: info
    service: api
- type: filestream
  id: api-error-log
  enabled: true
  paths:
    - /home/ec2-user/logs/error/*.json
  tags: ["error"]
  fields:
    log_level: error
    service: api
- type: filestream
  id: api-warn-log
  enabled: true
  paths:
    - /home/ec2-user/logs/warn/*.json
  tags: ["warn"]
  fields:
    log_level: warn
    service: api
```

그리고 변경사항을 반영하기 위해 아래의 명령어를 입력해서 서비스를 재시작하자.

```sh
sudo service filebeat start
```

### 로그 포맷 통일시키기
그러나 로그백 패턴에 따라 작성된 로그에서 유의미한 정보를 가져오기 위해서 파일비트의 전처리기에 각 항목이 어떤 항목인지를 패턴으로 나열해야 하는데, 이 부분을 해결하기 위해서 스프링의 로그백 설정에서 [ECS(Elastic Common Schema)](https://www.elastic.co/kr/blog/introducing-the-elastic-common-schema)를 따라 로그를 별도로 내보내도록 지정하기로 했다. ECS는 여러 시스템에서 만들어내는 로그들이 형식이 맞지 않아서 검색 및 시각화에 어려움이 있는데, 이러한 어려움을 해결하고자 만들어졌다고 한다.

아래와 같이 `build.gradle`에 의존성을 추가하자.

```groovy
// https://mvnrepository.com/artifact/co.elastic.logging/logback-ecs-encoder
implementation 'co.elastic.logging:logback-ecs-encoder:1.6.0'
```

그리고 로그백을 아래와 같이 구성하면 된다.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<included>
    <property name="JSON_FILE_LOG_PATH" value="./logs"/>

    <springProperty name="SERVICE_NAME" source="spring.application.name" />

    <appender name="INFO_JSON_FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${JSON_FILE_LOG_PATH}/info/info.json</file>
        <encoder class="co.elastic.logging.logback.EcsEncoder">
            <serviceName>${SERVICE_NAME}</serviceName>
        </encoder>
        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
            <fileNamePattern>${JSON_FILE_LOG_PATH}/info/info.%d{yyyy-MM-dd}-%i.json</fileNamePattern>
            <maxFileSize>100MB</maxFileSize>
            <maxHistory>14</maxHistory>
            <totalSizeCap>1GB</totalSizeCap>
        </rollingPolicy>
    </appender>

	<!-- ... -->
</included>
```

그 다음에 `logstash/config/logstash.conf`를 편집하자. 로그는 이제 JSON 포맷으로 출력되고 있으므로, 로그스태시에서 JSON 필터를 사용해 이 데이터를 파싱하고 구조화해야 한다.

```yml
filter {
    json {
	    # message 필드에 있는 JSON 문자열을 파싱함
	    # 파싱된 결과는 이벤트의 루트 레벨에 자동으로 추가됨
        source => "message"
    }
}
```
