### ISSUE TITLE
setup-java의 의존성 캐싱이 제대로 동작하지 않는 문제를 해결한다

### ISSUE THREAD

**Issue by yachimiya** [GU-99/grow-up-pms#52]
### 🐞 설명

캐시 키가 동일함에도 불구하고 setup-java에서 Gradle의 의존성 캐시를 찾지 못하는 문제가 있습니다.

![image](https://github.com/GU-99/grow-up-pms/assets/8318212/56cb95d8-943a-4826-9861-cb5c841f72f7)

setup-java는 내부적으로 `@actions/cache:v3.2.4`를 사용하는 것 같지만, `@actions/cache:v3-v4`에서 동일한 이슈가 발생하는 것을 확인했습니다. v2로 전환하고 문제 해결을 시도합니다.

### 📄 버그 로그

```shell
Run actions/setup-java@v4
Installed distributions
Creating settings.xml with server-id: github
Writing to /home/runner/.m2/settings.xml
gradle cache is not found
Run ./gradlew test --no-daemon
Downloading https://services.gradle.org/distributions/gradle-8.8-bin.zip
.............10%.............20%.............30%.............40%.............50%.............60%..............70%.............80%.............90%.............100%
```

### 🌏 버그 발생 환경

Ubuntu 22.04(20240609.1.0), Github Actions

### 📚 참고 자료

 - [cache restore on versions 3 and 4 not working](https://github.com/actions/cache/issues/1361)
 - [https://github.com/actions/cache/issues/1198](https://github.com/actions/cache/issues/1198)

### ⏰ 추정 시간

4시간

### ⏰ 소요 시간

4시간

**Comment by yachimiya** [comment]
아래와 같이 v2를 사용하도록 수정해도 동일한 문제가 발생합니다. 기존 PR에서는 한 번 캐싱하면 이후에는 잘 가져오는 것 같지만, 이후에 새로운 PR을 열면 의존성이 변경되지 않았음에도 불구하고 기존 캐시 키로 새롭게 캐싱하는 것을 확인할 수 있었습니다.

```yaml
      - name: Save Gradle cache
        uses: actions/cache@v2
        with:
          key: cache-gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            cache-gradle-${{ runner.os }}-
            cache-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
```

![image](https://github.com/GU-99/grow-up-pms/assets/8318212/72de8b40-0524-4ca4-9a92-bf1454af4190)
![image](https://github.com/GU-99/grow-up-pms/assets/8318212/e66eb4a4-a659-4874-a54f-7675ae7b50c0)
