### ISSUE TITLE
테스트에서 어떤 에러가 발생했는지 코멘트를 달아주는 액션을 추가한다

### ISSUE THREAD

**Issue by thornscript** [GU-99/grow-up-pms#85]
### 🎯 작업 목표

CI 파이프라인에서 테스트와 관련된 워크플로우가 실행되었을 때, 중간에 테스트 프레임워크에서 에러가 발생하면 어느 부분에서 문제가 발생했는지 팀원에게 빠르게 피드백을 주는 것이 좋을 것 같다고 생각했습니다. 에러가 발생했는데 Github Actions의 잡 로그를 스크롤하며 무엇이 문제였는지 찾는 것은 상당히 번거로운 일이기 때문입니다.

### ✅ 작업할 내용

- [x] 액션을 통해서 테스트 에러 발생 시 발생 위치에 코멘트를 달아주도록 함

### ⏰ 추정 시간

30분

### ⏰ 소요 시간

30분

**Comment by thornscript** [comment]
이러한 필요성을 느끼고 마켓플레이스에서 찾아보다가 `action-junit-report`를 발견했는데, JUnit 테스트 실행 후 생성된 `./build/test-results/test/TEST-*.xml`을 이용해 테스트 케이스가 터지면 해당 케이스에서 발생한 오류 메시지를 코드에다가 코멘트를 달아주는 것 같습니다. 다른 액션도 찾아봤지만 코멘트가 좀 빈약해서 최종적으로 `action-junit-report`를 선택하게 되었습니다. :smile: 

![image](https://github.com/user-attachments/assets/8f8343eb-758b-43e8-911a-d8b1d4ede760)

```yml
name: build
on:
  pull_request:

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build and Run Tests
        run: # execute your tests generating test results
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
```
